### ISSUE TITLE
有关AEGCN-BERT模型的问题

### ISSUE THREAD

**Issue by yesxiaoyu** [Xillv/Code-for-AEGCN-Glove#1]
您好，感谢您对论文AEGCN-GloVe代码的分享。我将句法信息融入BERT，但是遇到subword问题，导致句法依存树的节点与输入的token无法对应。请问您是如何处理的，期待您的回复。

**Comment by Xillv** [comment]
关于BERT要重新写一个邻接矩阵的生成代码，使得邻接矩阵的格式也与BERT的格式对应

**Comment by Xillv** [comment]
> 您好，感谢您对论文AEGCN-GloVe代码的分享。我将句法信息融入BERT，但是遇到subword问题，导致句法依存树的节点与输入的token无法对应。请问您是如何处理的，期待您的回复。

**Comment by yesxiaoyu** [comment]
非常感谢您的回复，BERT的输入是 “[CLS] + context + [SEP]” 和 “[CLS] +target + [SEP]”的形式 ，请问在计算邻接矩阵的时候，是使用BERT的Tokenizer分词，然后再根据Spacy得到的吗？

**Comment by Xillv** [comment]
从Bert-transformers那个库调用tokenizer的那个方法，把文本变成Bert专属的token，然后将这个token作为输入，调用spacy包做依存句法分析得到token间的依存关系，然后用这个依存关系构建Bert版本的邻接矩阵

**Comment by yesxiaoyu** [comment]
好的，非常感谢您的回复。
